import { useEffect, useState } from "react";
import { Activity, Lightbulb, Share2, CheckCircle2 } from "lucide-react";
import { useStore } from "../../store/store";
import { Card, SectionHeader, Chip, Button } from "../../components/ui/ui";
import { AgentThinking } from "../../components/agent/AgentBits";
import { patterns } from "../../mock/seed";
import { api, type GeneratedLesson } from "../../lib/api";

export function Patterns() {
  const lessons = useStore((s) => s.lessons);
  const publishLesson = useStore((s) => s.publishLesson);
  const pushToast = useStore((s) => s.pushToast);
  const p = patterns[0]; // mock pattern DATA (events, area, hazard, count, related)

  // The ANALYSIS + lesson text are generated by the Incident Intelligence agent (LLM).
  const [lesson, setLesson] = useState<GeneratedLesson | null>(null);
  const [loading, setLoading] = useState(true);
  const seedLesson = lessons[0];

  useEffect(() => {
    setLoading(true);
    api
      .lesson({ area: p.area, hazard: p.hazard, count: p.count, window: p.window, related: p.related })
      .then((l) => setLesson(l))
      .catch(() => setLesson(null))
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="p-6 max-w-5xl mx-auto">
      <SectionHeader title="Recurring Patterns & Lessons Learned" subtitle="Systemic learning from incidents + near-misses" />

      <Card className="p-5 border-l-4 border-l-safety-red mb-5">
        <div className="flex items-start gap-3">
          <span className="grid h-10 w-10 place-items-center rounded-xl bg-red-50 text-safety-red"><Activity size={20} /></span>
          <div className="flex-1">
            <div className="flex items-center gap-2">
              <h3 className="font-bold text-navy-900">{p.title}</h3>
              <Chip tone="red">{p.count} events / {p.window}</Chip>
            </div>
            {/* Common-factor analysis comes from the LLM, with the mock pattern as fallback */}
            <p className="mt-1 text-sm text-navy-800">
              Common factor:{" "}
              <strong>{loading ? "analysing…" : lesson?.insight ?? p.commonFactor}</strong>
            </p>
            <div className="mt-2 flex flex-wrap gap-1.5">
              {p.related.map((r) => <Chip key={r} tone="slate">{r}</Chip>)}
            </div>
          </div>
        </div>
      </Card>

      <Card className="p-5">
        <div className="flex items-center gap-2 mb-2">
          <Lightbulb className="text-safety-amber" />
          <h3 className="font-bold text-navy-900">AI-generated lesson learned</h3>
          {lesson?.mode === "azure" && <Chip tone="blue"><Lightbulb size={12} /> Live</Chip>}
          {seedLesson.published && <Chip tone="green"><CheckCircle2 size={12} /> Published to KB</Chip>}
        </div>

        {loading ? (
          <AgentThinking label="Incident Intelligence agent is analysing the pattern…" />
        ) : (
          <>
            <p className="font-semibold text-navy-900">{lesson?.title ?? seedLesson.title}</p>
            <p className="mt-1 text-sm text-navy-800 leading-relaxed">{lesson?.summary ?? seedLesson.summary}</p>
            <div className="mt-3 rounded-lg bg-green-50 border border-green-100 p-3 text-sm text-green-800">
              <strong>Recommended control:</strong> {lesson?.control ?? seedLesson.control}
            </div>
            <div className="mt-2 flex flex-wrap gap-1.5">
              {(lesson?.standards ?? seedLesson.standards).map((s) => <Chip key={s} tone="blue">{s}</Chip>)}
            </div>
            <div className="mt-4">
              <Button
                variant={seedLesson.published ? "secondary" : "primary"}
                disabled={seedLesson.published}
                onClick={() => {
                  publishLesson(seedLesson.id);
                  pushToast({ title: "Lesson published to Knowledge Base", detail: "Shared to all HSE users", variant: "success" });
                }}
              >
                <Share2 size={15} /> {seedLesson.published ? "Published" : "Publish to Knowledge Base"}
              </Button>
            </div>
          </>
        )}
      </Card>
    </div>
  );
}
