import { useEffect, useState } from "react";
import { Activity, Lightbulb, Share2, CheckCircle2, Loader2 } from "lucide-react";
import { useStore } from "../../store/store";
import { Card, SectionHeader, Chip, Button } from "../../components/ui/ui";
import { patterns } from "../../mock/seed";
import { api, isDisabled, type GeneratedLesson } from "../../lib/api";

export function Patterns() {
  const lessons = useStore((s) => s.lessons);
  const publishLesson = useStore((s) => s.publishLesson);
  const pushToast = useStore((s) => s.pushToast);
  const p = patterns[0]; // mock pattern DATA (events, area, hazard, count, related)
  const seedLesson = lessons[0];

  // The analysis + lesson text are generated by the Incident Intelligence agent (LLM).
  // We show the seeded lesson immediately, then swap in the live analysis when it
  // arrives — so the tab is never stuck on a blank loader.
  const [lesson, setLesson] = useState<GeneratedLesson | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let alive = true;
    setLoading(true);
    api
      .lesson({ area: p.area, hazard: p.hazard, count: p.count, window: p.window, related: p.related })
      .then((l) => {
        if (alive && !isDisabled(l)) setLesson(l);
      })
      .catch(() => {/* keep seed content */})
      .finally(() => alive && setLoading(false));
    return () => {
      alive = false;
    };
  }, []);

  // Live result if we have it, otherwise the seeded lesson.
  const insight = lesson?.insight ?? p.commonFactor;
  const title = lesson?.title ?? seedLesson.title;
  const summary = lesson?.summary ?? seedLesson.summary;
  const control = lesson?.control ?? seedLesson.control;
  const standards = lesson?.standards ?? seedLesson.standards;

  return (
    <div className="p-6 max-w-5xl mx-auto">
      <SectionHeader title="Recurring Patterns & Lessons Learned" subtitle="Systemic learning from incidents + near-misses" />

      <Card className="p-5 border-l-4 border-l-safety-red mb-5">
        <div className="flex items-start gap-3">
          <span className="grid h-10 w-10 place-items-center rounded-xl bg-red-50 text-safety-red"><Activity size={20} /></span>
          <div className="flex-1">
            <div className="flex items-center gap-2">
              <h3 className="font-bold text-navy-900">{p.title}</h3>
              <Chip tone="red">{p.count} events / {p.window}</Chip>
            </div>
            <p className="mt-1 text-sm text-navy-800">
              Common factor: <strong>{insight}</strong>
            </p>
            <div className="mt-2 flex flex-wrap gap-1.5">
              {p.related.map((r) => <Chip key={r} tone="slate">{r}</Chip>)}
            </div>
          </div>
        </div>
      </Card>

      <Card className="p-5">
        <div className="flex items-center gap-2 mb-2">
          <Lightbulb className="text-safety-amber" />
          <h3 className="font-bold text-navy-900">AI-generated lesson learned</h3>
          {loading && (
            <Chip tone="amber"><Loader2 size={12} className="animate-spin" /> Analysing live…</Chip>
          )}
          {!loading && lesson?.mode === "azure" && (
            <Chip tone="blue"><Lightbulb size={12} /> Live</Chip>
          )}
          {seedLesson.published && <Chip tone="green"><CheckCircle2 size={12} /> Published to KB</Chip>}
        </div>

        <p className="font-semibold text-navy-900">{title}</p>
        <p className="mt-1 text-sm text-navy-800 leading-relaxed">{summary}</p>
        <div className="mt-3 rounded-lg bg-green-50 border border-green-100 p-3 text-sm text-green-800">
          <strong>Recommended control:</strong> {control}
        </div>
        <div className="mt-2 flex flex-wrap gap-1.5">
          {standards.map((s, i) => <Chip key={`${s}-${i}`} tone="blue">{s}</Chip>)}
        </div>
        <div className="mt-4">
          <Button
            variant={seedLesson.published ? "secondary" : "primary"}
            disabled={seedLesson.published}
            onClick={() => {
              publishLesson(seedLesson.id);
              pushToast({ title: "Lesson published to Knowledge Base", detail: "Shared to all HSE users", variant: "success" });
            }}
          >
            <Share2 size={15} /> {seedLesson.published ? "Published" : "Publish to Knowledge Base"}
          </Button>
        </div>
      </Card>
    </div>
  );
}
