import { useState } from "react";
import { FileText, Download, Loader2, Sparkles } from "lucide-react";
import { useStore } from "../../store/store";
import { Card, SectionHeader, Button, Dialog, Chip } from "../../components/ui/ui";
import { api, type GeneratedReport } from "../../lib/api";

const templates = [
  { id: "monthly", name: "Monthly HSE Summary", desc: "KPIs, trends, open actions" },
  { id: "incident", name: "Incident Pack", desc: "ICAM investigations + corrective actions" },
  { id: "compliance", name: "Compliance Status", desc: "SOP currency + standard alignment" },
];

export function Reports() {
  const [loading, setLoading] = useState<string | null>(null);
  const [open, setOpen] = useState(false);
  const [report, setReport] = useState<GeneratedReport | null>(null);
  const pushToast = useStore((s) => s.pushToast);

  const gen = async (id: string) => {
    setLoading(id);
    try {
      const r = await api.report(id);
      setReport(r);
      setOpen(true);
    } catch {
      pushToast({ title: "Could not reach the reporting agent", detail: "Is the backend running on :8000?", variant: "error" });
    }
    setLoading(null);
  };

  return (
    <div className="p-6 max-w-5xl mx-auto">
      <SectionHeader title="Reports" subtitle="Board-ready, AI-generated HSE reports" />
      <div className="grid sm:grid-cols-3 gap-4">
        {templates.map((t) => (
          <Card key={t.id} className="p-5">
            <FileText size={26} className="text-brand" />
            <h3 className="mt-3 font-bold text-navy-900">{t.name}</h3>
            <p className="text-xs text-slate-500 mt-1">{t.desc}</p>
            <Button className="mt-4 w-full" onClick={() => gen(t.id)} disabled={!!loading}>
              {loading === t.id ? (
                <><Loader2 size={15} className="animate-spin" /> Generating…</>
              ) : (
                <><Sparkles size={14} /> Generate</>
              )}
            </Button>
          </Card>
        ))}
      </div>

      <Dialog open={open} onClose={() => setOpen(false)} title={report ? `${report.title} · ${report.period}` : ""} size="lg">
        {report && (
          <div className="p-6">
            <div className="rounded-xl border border-slate-300 bg-white p-6">
              <div className="flex items-center justify-between border-b border-slate-200 pb-3">
                <div>
                  <p className="font-extrabold text-navy-900 text-lg">{report.title}</p>
                  <p className="text-xs text-slate-500">Black Mountain · {report.period}</p>
                </div>
                <div className="flex items-center gap-2">
                  {report.mode === "azure" && <Chip tone="blue"><Sparkles size={12} /> AI-generated</Chip>}
                  <Chip tone="slate">POPIA · Internal (C3)</Chip>
                </div>
              </div>

              <p className="mt-4 text-sm text-navy-800 leading-relaxed font-medium">{report.summary}</p>

              <div className="mt-4 space-y-3">
                {report.sections.map((s, i) => (
                  <div key={i}>
                    <p className="text-xs font-bold uppercase tracking-wide text-slate-500">{s.heading}</p>
                    <p className="text-sm text-navy-800 leading-relaxed mt-0.5">{s.body}</p>
                  </div>
                ))}
              </div>

              <p className="mt-6 text-[10px] text-slate-400 border-t border-slate-200 pt-2">
                Zensar · Generated by Zen-Sentinel reporting agent
              </p>
            </div>
            <div className="mt-4 flex justify-end">
              <Button onClick={() => { window.print(); pushToast({ title: "Report downloaded", variant: "success" }); }}>
                <Download size={15} /> Download
              </Button>
            </div>
          </div>
        )}
      </Dialog>
    </div>
  );
}
